/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the LICENSE
 * file in the root directory of this source tree.
 */
#pragma once

#include <chrono>

#include <folly/Conv.h>
#include <folly/Range.h>
#include <folly/io/async/AsyncTransport.h>
#include <folly/io/async/DelayedDestruction.h>
#include <folly/io/async/VirtualEventBase.h>
#include <thrift/lib/cpp/async/TAsyncSocket.h>

#include "mcrouter/lib/Reply.h"
#include "mcrouter/lib/mc/protocol.h"
#include "mcrouter/lib/network/ConnectionOptions.h"
#include "mcrouter/lib/network/RpcStatsContext.h"
#include "mcrouter/lib/network/SecurityOptions.h"
#include "mcrouter/lib/network/Transport.h"

namespace facebook {
namespace memcache {

/**
 * Represents a Thrift Transport.
 * The concrete thrift transport class is generated by carbon compiler.
 */
class ThriftTransportBase : public Transport,
                            public folly::DelayedDestruction,
                            private folly::AsyncSocket::ConnectCallback {
 public:
  ThriftTransportBase(
      folly::VirtualEventBase& eventBase,
      ConnectionOptions options);
  virtual ~ThriftTransportBase() override = default;

  static constexpr folly::StringPiece name() {
    return "ThriftTransport";
  }

  static constexpr bool isCompatible(mc_protocol_t protocol) {
    return protocol == mc_thrift_protocol;
  }

  void closeNow() override final;

  void setConnectionStatusCallbacks(
      ConnectionStatusCallbacks callbacks) override final;

  void setRequestStatusCallbacks(
      RequestStatusCallbacks callbacks) override final;

  void setThrottle(size_t maxInflight, size_t maxPending) override final;

  RequestQueueStats getRequestQueueStats() const override final;

  void updateTimeoutsIfShorter(
      std::chrono::milliseconds /* connectTimeout */,
      std::chrono::milliseconds /* writeTimeout */) override final;

  const folly::AsyncTransportWrapper* getTransport() const override final;

  double getRetransmitsPerKb() override final;

  void setFlushList(FlushList* /* flushList */) override final;

 protected:
  enum class ConnectionState {
    Up, // Connection is open and we can write into it.
    Down, // Connection is not open (or close), we need to reconnect.
    Connecting, // Currently connecting.
    Error // Currently processing error.
  };

  folly::EventBase& eventBase_;
  const ConnectionOptions connectionOptions_;

  // Connection and client related fields.
  folly::AsyncTransportWrapper::UniquePtr socket_;
  ConnectionState connectionState_{ConnectionState::Down};

  // Callbacks
  ConnectionStatusCallbacks connectionCallbacks_;
  RequestStatusCallbacks requestCallbacks_;

  // Throttle options (disabled by default).
  size_t maxInflight_{0};
  size_t maxPending_{0};

 private:
  // AsyncSocket::ConnectCallback overrides
  void connectSuccess() noexcept final;
  void connectErr(const folly::AsyncSocketException& ex) noexcept final;
};

template <class RouterInfo>
class ThriftTransport : public ThriftTransportBase {
 public:
  ThriftTransport(folly::VirtualEventBase& eventBase, ConnectionOptions options)
      : ThriftTransportBase(eventBase, std::move(options)) {}
  ~ThriftTransport() override final = default;

  template <class Request>
  ReplyT<Request> sendSync(
      const Request& /* request */,
      std::chrono::milliseconds /* timeout */,
      RpcStatsContext* /* rpcContext */ = nullptr) {
    throw std::logic_error(folly::to<std::string>(
        "Router ", RouterInfo::name, " does not support thrift transport"));
  }
};

} // namespace memcache
} // namespace facebook
