namespace carbon::test2::util;

enum SimpleEnum : int64_t {
  Twenty = 20,
  Zero = 0,
  One = 1,
  Negative = -92233
};

struct SimpleStruct {
  1: int64_t member1;
};

union SimpleUnion {
  1: int64_t umember1;
  2: bool umember2;
  3: std::string umember3;
};

request YetAnotherRequest {
  id: 2;
  name: "yet_another";
  reply: YetAnotherReply;

  1: carbon::Keys<folly::IOBuf> key;
};

reply YetAnotherReply {
  1: Result result;
};
