namespace carbon::test;

import "mcrouter/lib/carbon/test/a/b/B.idl"

struct BaseStruct {
  1: int64_t baseInt64Member;
};

struct SimpleStruct with 1: BaseStruct {
  1: int32_t int32Member;
  2: std::string stringMember;
  3: test2::util::SimpleEnum enumMember;
  4: std::vector<test2::util::SimpleStruct> vectorMember;
};
