FROM ubuntu:bionic
MAINTAINER Ori Shalev (orish@fb.com)
RUN apt-get update && apt-get install -y libdouble-conversion1 openssl libgflags2.2 libgoogle-glog0v5 libboost-context1.65.1 libboost-filesystem1.65.1 libboost-program-options1.65.1 libboost-regex1.65.1 libevent-dev libsodium23
RUN apt-get install -y netcat
RUN mkdir /packages
VOLUME /packages
COPY config.json /root/config.json

#CMD bash
