# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

gen_ref_api_only;
namespace carbon::test_enum;
thrift_namespace carbon.test_enum.thrift;

enum Foo {
  BAR = 1,
  BAZ = 2,
};

struct StructWithEnumField {
  1: Foo test;
};
