namespace hellogoodbye;

import "mcrouter/lib/network/Common.idl"

request HelloRequest {
  id: 1;
  name: "hello";
  reply: HelloReply;

  1: carbon::Keys<folly::IOBuf> key;
  2: uint64_t shardId;
};

reply HelloReply {
  1: Result result;
};

request GoodbyeRequest {
  id: 2;
  name: "goodbye";
  reply: GoodbyeReply;

  1: carbon::Keys<folly::IOBuf> key;
  2: uint64_t shardId;
};

reply GoodbyeReply {
  1: Result result;
  2: std::string message;
};

service {
  additional_route_handles: [
    DuplicateRoute @ "mcrouter/lib/carbon/example/DuplicateRoute.h"
  ];
  gen_client_tool: true;
};
